import { describe, expect, it } from 'vitest'
import { resolveSegments } from '../pathResolver'
import { LineSegment, PathSettings, Segment } from '../../types'

const makeLine = (id: string, length: number, heading: number): LineSegment => ({
  id,
  type: 'line',
  lengthMm: length,
  headingDeg: heading,
  enabled: true,
  label: id,
  profile: {
    shape: 'trapezoid',
    startMmS: 0,
    cruiseMmS: 120,
    endMmS: 0,
    accelMmS2: 300,
    decelMmS2: 300,
  },
})

describe('resolveSegments', () => {
  const settings: PathSettings = {
    autoCorners: {
      mode: 'fillet_then_turn',
      minRadiusMm: 100,
      maxFilletSweepDeg: 120,
    },
  }

  it('returns auto-generated fillet between non-tangent lines', () => {
    const segments: Segment[] = [
      makeLine('a', 400, 0),
      makeLine('b', 400, 90),
    ]
    const result = resolveSegments({ segments, settings })
    const autoFillet = result.segments.find((segment) => segment.autoGenerated && segment.type === 'arc')
    expect(autoFillet).toBeTruthy()
    expect(autoFillet?.segment.type).toBe('arc')
    expect(result.segments.length).toBeGreaterThan(segments.length)
  })

  it('falls back to turn when fillet not feasible', () => {
    const segments: Segment[] = [
      makeLine('a', 100, 0),
      makeLine('b', 100, 170),
    ]
    const result = resolveSegments({
      segments,
      settings: {
        autoCorners: {
          ...settings.autoCorners,
          minRadiusMm: 500,
        },
      },
    })
    const autoTurn = result.segments.find((segment) => segment.autoGenerated && segment.type === 'turn')
    expect(autoTurn).toBeTruthy()
  })

  it('ignores corners when mode is off', () => {
    const segments: Segment[] = [
      makeLine('a', 200, 0),
      makeLine('b', 200, -90),
    ]
    const result = resolveSegments({
      segments,
      settings: {
        autoCorners: { ...settings.autoCorners, mode: 'off' },
      },
    })
    expect(result.segments.length).toBe(segments.length)
  })
})
