import type { PathDocument } from '../store/usePathStore'
import type { AngularSpeedProfile, LinearSpeedProfile, ResolvedSegment } from '../types'
import { distance } from './geometry'

const indent = (text: string, spaces = 2) =>
  text
    .split('\n')
    .map((line) => `${' '.repeat(spaces)}${line}`)
    .join('\n')

const toPythonBool = (value: boolean) => (value ? 'True' : 'False')

const sanitizeLabel = (label: string) => JSON.stringify(label).slice(1, -1)

type SegmentPayload = {
  id: string
  label: string
  enabled: boolean
  type: ResolvedSegment['type']
  auto: boolean
  start_heading_deg: number
  end_heading_deg: number
  length_mm?: number
  heading_deg?: number
  radius_mm?: number
  angle_deg?: number
  entry_heading_deg?: number
  control?: string
  profile?: LinearSpeedProfile | AngularSpeedProfile
}

const buildSegmentsPayload = (segments: ResolvedSegment[]) => {
  return segments.map((segment) => {
    const base = segment.segment
    const payload: SegmentPayload = {
      id: base.id,
      label: base.label ?? base.id,
      enabled: base.enabled,
      type: segment.type,
      auto: segment.autoGenerated,
      start_heading_deg: Number(segment.start.headingDeg.toFixed(4)),
      end_heading_deg: Number(segment.end.headingDeg.toFixed(4)),
    }
    if (segment.type === 'line' && base.type === 'line') {
      const length = distance(segment.start.x, segment.start.y, segment.end.x, segment.end.y)
      payload.length_mm = Number(length.toFixed(4))
      payload.heading_deg = base.headingDeg
      payload.profile = base.profile
    }
    if (segment.type === 'arc' && base.type === 'arc') {
      payload.radius_mm = base.radiusMm
      payload.angle_deg = base.angleDeg
      payload.entry_heading_deg = base.entryHeadingDeg
      const length = Math.abs((Math.PI * base.radiusMm * base.angleDeg) / 180)
      payload.length_mm = Number(length.toFixed(4))
      payload.profile = base.profile
    }
    if (segment.type === 'turn' && base.type === 'turn') {
      payload.angle_deg = base.angleDeg
      payload.control = base.control
      payload.profile = base.profile
    }
    return payload
  })
}

export const generatePybricksScript = (
  doc: PathDocument,
  segments: ResolvedSegment[],
) => {
  const robot = doc.robot
  const segmentPayload = buildSegmentsPayload(segments)
  const lines: string[] = []

  lines.push('# generated by HUBConnector')
  lines.push('from pybricks.hubs import PrimeHub')
  lines.push('from pybricks.pupdevices import Motor')
  lines.push('from pybricks.parameters import Port, Stop, Direction')
  lines.push('from pybricks.tools import StopWatch, wait')
  lines.push('import math')
  lines.push('')
  lines.push('hub = PrimeHub()')
  const leftDirection = robot.invert.left ? 'Direction.COUNTERCLOCKWISE' : 'Direction.CLOCKWISE'
  const rightDirection = robot.invert.right ? 'Direction.COUNTERCLOCKWISE' : 'Direction.CLOCKWISE'
  lines.push(
    `left_motor = Motor(Port.${robot.ports.left}, positive_direction=${leftDirection})`,
  )
  lines.push(
    `right_motor = Motor(Port.${robot.ports.right}, positive_direction=${rightDirection})`,
  )
  if (robot.ports.aux.length > 0) {
    lines.push('aux_motors = {')
    robot.ports.aux.forEach((aux) => {
      const invert = robot.invert.aux?.[aux.id] ?? false
      const direction = invert ? 'Direction.COUNTERCLOCKWISE' : 'Direction.CLOCKWISE'
      lines.push(
        indent(
          `"${sanitizeLabel(aux.id)}": Motor(Port.${aux.port}, positive_direction=${direction}),`,
          2,
        ),
      )
    })
    lines.push('}')
  } else {
    lines.push('aux_motors = {}')
  }
  lines.push('')
  lines.push(`WHEEL_DIAMETER_MM = ${robot.wheel.diameterMm}`)
  lines.push(`WHEEL_CIRCUMFERENCE_MM = ${robot.wheel.circumferenceMm}`)
  lines.push(`GEAR_RATIO = ${robot.gearRatio}`)
  lines.push('EFFECTIVE_CIRCUMFERENCE_MM = WHEEL_CIRCUMFERENCE_MM / GEAR_RATIO')
  lines.push(`TRACK_WIDTH_MM = ${robot.trackWidthMm}`)
  lines.push('')
  lines.push('GYRO_CFG = {')
  lines.push(indent(`"enabled": ${toPythonBool(robot.gyro.enabled)},`))
  lines.push(indent(`"kp": ${robot.gyro.kp},`))
  lines.push(indent(`"ki": ${robot.gyro.ki},`))
  lines.push(indent(`"kd": ${robot.gyro.kd},`))
  lines.push(indent(`"sample_ms": ${robot.gyro.sampleMs},`))
  lines.push(indent(`"max_correction_deg_s": ${robot.gyro.maxCorrectionDegS},`))
  lines.push(indent(`"tolerance_deg": ${robot.gyro.toleranceDeg}`))
  lines.push('}')
  lines.push('')
  lines.push('watch = StopWatch()')
  lines.push('')
  lines.push('def mm_to_deg(mm):')
  lines.push(indent('return (mm / EFFECTIVE_CIRCUMFERENCE_MM) * 360'))
  lines.push('')
  lines.push('def deg_to_mm(deg):')
  lines.push(indent('return (deg / 360) * EFFECTIVE_CIRCUMFERENCE_MM'))
  lines.push('')
  lines.push('def speed_mm_to_deg(speed):')
  lines.push(indent('return (speed / EFFECTIVE_CIRCUMFERENCE_MM) * 360'))
  lines.push('')
  lines.push('def normalize_angle(deg):')
  lines.push(indent('while deg > 180:'))
  lines.push(indent('deg -= 360', 4))
  lines.push(indent('while deg <= -180:'))
  lines.push(indent('deg += 360', 4))
  lines.push(indent('return deg'))
  lines.push('')
  lines.push('class PID:')
  lines.push(indent('def __init__(self, kp, ki, kd, limit):'))
  lines.push(indent('self.kp = kp', 4))
  lines.push(indent('self.ki = ki', 4))
  lines.push(indent('self.kd = kd', 4))
  lines.push(indent('self.limit = limit', 4))
  lines.push(indent('self.integral = 0', 4))
  lines.push(indent('self.prev_error = 0', 4))
  lines.push('')
  lines.push(indent('def update(self, error, dt):'))
  lines.push(indent('self.integral += error * dt', 4))
  lines.push(indent('derivative = 0 if dt == 0 else (error - self.prev_error) / dt', 4))
  lines.push(indent('self.prev_error = error', 4))
  lines.push(indent('output = self.kp * error + self.ki * self.integral + self.kd * derivative', 4))
  lines.push(indent('if self.limit:', 4))
  lines.push(indent('output = max(min(output, self.limit), -self.limit)', 6))
  lines.push(indent('return output', 4))
  lines.push('')
  lines.push('def profile_speed(profile, progress):')
  lines.push(indent('shape = profile.get("shape", "trapezoid")'))
  lines.push(indent('if shape == "s_curve":'))
  lines.push(indent('ease = 0.5 - 0.5 * math.cos(progress * math.pi)', 4))
  lines.push(indent('else:', 4))
  lines.push(indent('ease = progress', 6))
  lines.push(indent('start = profile.get("startMmS") or profile.get("startDegS") or 0', 4))
  lines.push(indent('cruise = profile.get("cruiseMmS") or profile.get("cruiseDegS") or 0', 4))
  lines.push(indent('end = profile.get("endMmS") or profile.get("endDegS") or 0', 4))
  lines.push(indent('if ease < 0.5:', 4))
  lines.push(indent('return start + (cruise - start) * (ease * 2)', 6))
  lines.push(indent('else:', 4))
  lines.push(indent('return cruise + (end - cruise) * ((ease - 0.5) * 2)', 6))
  lines.push('')
  lines.push('def apply_inversion(left, right):')
  lines.push(indent(`if ${toPythonBool(robot.invert.left)}:`))
  lines.push(indent('left = -left', 4))
  lines.push(indent(`if ${toPythonBool(robot.invert.right)}:`))
  lines.push(indent('right = -right', 4))
  lines.push(indent('return left, right'))
  lines.push('')
  lines.push('def drive_line(segment):')
  lines.push(indent('length_mm = segment["length_mm"]'))
  lines.push(indent('heading_start = segment["start_heading_deg"]'))
  lines.push(indent('heading_target = segment["heading_deg"]'))
  lines.push(indent('profile = segment["profile"]'))
  lines.push(indent('direction = 1 if length_mm >= 0 else -1'))
  lines.push(indent('total_deg = abs(mm_to_deg(length_mm))'))
  lines.push(indent('if total_deg == 0:'))
  lines.push(indent('return', 4))
  lines.push(indent('pid = PID(GYRO_CFG["kp"], GYRO_CFG["ki"], GYRO_CFG["kd"], GYRO_CFG["max_correction_deg_s"])'))
  lines.push(indent('left_motor.reset_angle(0)'))
  lines.push(indent('right_motor.reset_angle(0)'))
  lines.push(indent('while True:'))
  lines.push(indent('avg_deg = (abs(left_motor.angle()) + abs(right_motor.angle())) / 2', 4))
  lines.push(indent('progress = min(1, avg_deg / total_deg)', 4))
  lines.push(indent('target_speed = profile_speed(profile, progress)', 4))
  lines.push(indent('base_speed = speed_mm_to_deg(target_speed) * direction', 4))
  lines.push(indent('correction = 0', 4))
  lines.push(indent('if GYRO_CFG["enabled"]:', 4))
  lines.push(indent('desired_heading = heading_start + (heading_target - heading_start) * progress', 6))
  lines.push(indent('error = normalize_angle(desired_heading - hub.imu.heading())', 6))
  lines.push(indent('correction = pid.update(error, GYRO_CFG["sample_ms"] / 1000)', 6))
  lines.push(indent('correction = max(min(correction, GYRO_CFG["max_correction_deg_s"]), -GYRO_CFG["max_correction_deg_s"])', 6))
  lines.push(indent('left_speed, right_speed = apply_inversion(base_speed - correction, base_speed + correction)', 4))
  lines.push(indent('left_motor.run(left_speed)', 4))
  lines.push(indent('right_motor.run(right_speed)', 4))
  lines.push(indent('if progress >= 1:', 4))
  lines.push(indent('break', 6))
  lines.push(indent('wait(GYRO_CFG["sample_ms"])', 4))
  lines.push(indent('left_motor.stop(Stop.HOLD)'))
  lines.push(indent('right_motor.stop(Stop.HOLD)'))
  lines.push('')
  lines.push('def drive_arc(segment):')
  lines.push(indent('radius = segment["radius_mm"]'))
  lines.push(indent('angle = segment["angle_deg"]'))
  lines.push(indent('profile = segment["profile"]'))
  lines.push(indent('heading_start = segment["start_heading_deg"]'))
  lines.push(indent('total_angle = abs(angle)'))
  lines.push(indent('if total_angle == 0:'))
  lines.push(indent('return', 4))
  lines.push(indent('direction = 1 if angle >= 0 else -1'))
  lines.push(indent('pid = PID(GYRO_CFG["kp"], GYRO_CFG["ki"], GYRO_CFG["kd"], GYRO_CFG["max_correction_deg_s"])'))
  lines.push(indent('inner = radius - direction * (TRACK_WIDTH_MM / 2)'))
  lines.push(indent('outer = radius + direction * (TRACK_WIDTH_MM / 2)'))
  lines.push(indent('left_ratio = inner / radius'))
  lines.push(indent('right_ratio = outer / radius'))
  lines.push(indent('if direction < 0:'))
  lines.push(indent('left_ratio, right_ratio = right_ratio, left_ratio', 4))
  lines.push(indent('arc_length = abs(math.pi * radius * angle / 180)'))
  lines.push(indent('left_motor.reset_angle(0)'))
  lines.push(indent('right_motor.reset_angle(0)'))
  lines.push(indent('while True:'))
  lines.push(indent('left_mm = abs(deg_to_mm(left_motor.angle()))', 4))
  lines.push(indent('right_mm = abs(deg_to_mm(right_motor.angle()))', 4))
  lines.push(indent('avg_mm = (left_mm + right_mm) / 2', 4))
  lines.push(indent('progress = min(1, avg_mm / arc_length)', 4))
  lines.push(indent('target_speed = profile_speed(profile, progress)', 4))
  lines.push(indent('base = speed_mm_to_deg(target_speed)', 4))
  lines.push(indent('correction = 0', 4))
  lines.push(indent('if GYRO_CFG["enabled"]:', 4))
  lines.push(indent('desired_heading = heading_start + angle * progress', 6))
  lines.push(indent('error = normalize_angle(desired_heading - hub.imu.heading())', 6))
  lines.push(indent('correction = pid.update(error, GYRO_CFG["sample_ms"] / 1000)', 6))
  lines.push(indent('correction = max(min(correction, GYRO_CFG["max_correction_deg_s"]), -GYRO_CFG["max_correction_deg_s"])', 6))
  lines.push(indent('left_speed = (base * left_ratio * direction) - correction', 4))
  lines.push(indent('right_speed = (base * right_ratio * direction) + correction', 4))
  lines.push(indent('left_speed, right_speed = apply_inversion(left_speed, right_speed)', 4))
  lines.push(indent('left_motor.run(left_speed)', 4))
  lines.push(indent('right_motor.run(right_speed)', 4))
  lines.push(indent('if progress >= 1:', 4))
  lines.push(indent('break', 6))
  lines.push(indent('wait(GYRO_CFG["sample_ms"])', 4))
  lines.push(indent('left_motor.stop(Stop.HOLD)'))
  lines.push(indent('right_motor.stop(Stop.HOLD)'))
  lines.push('')
  lines.push('def turn_in_place(segment):')
  lines.push(indent('angle = segment["angle_deg"]'))
  lines.push(indent('profile = segment["profile"]'))
  lines.push(indent('control = segment.get("control", "gyro")'))
  lines.push(indent('degrees = abs(mm_to_deg(math.pi * TRACK_WIDTH_MM * (angle / 360)))'))
  lines.push(indent('pid = PID(GYRO_CFG["kp"], GYRO_CFG["ki"], GYRO_CFG["kd"], GYRO_CFG["max_correction_deg_s"])'))
  lines.push(indent('left_motor.reset_angle(0)'))
  lines.push(indent('right_motor.reset_angle(0)'))
  lines.push(indent('direction = 1 if angle >= 0 else -1'))
  lines.push(indent('while True:'))
  lines.push(indent('avg_deg = (abs(left_motor.angle()) + abs(right_motor.angle())) / 2', 4))
  lines.push(indent('progress = min(1, avg_deg / degrees)', 4))
  lines.push(indent('target_speed = profile_speed(profile, progress)', 4))
  lines.push(indent('wheel_mm_s = math.pi * TRACK_WIDTH_MM * (target_speed / 360)', 4))
  lines.push(indent('base = speed_mm_to_deg(wheel_mm_s) * direction', 4))
  lines.push(indent('left_speed, right_speed = apply_inversion(-base, base)', 4))
  lines.push(indent('if control == "gyro" and GYRO_CFG["enabled"]:', 4))
  lines.push(indent('target_heading = hub.imu.heading() + angle', 6))
  lines.push(indent('error = normalize_angle(target_heading - hub.imu.heading())', 6))
  lines.push(indent('correction = pid.update(error, GYRO_CFG["sample_ms"] / 1000)', 6))
  lines.push(indent('left_speed -= correction', 6))
  lines.push(indent('right_speed += correction', 6))
  lines.push(indent('left_motor.run(left_speed)', 4))
  lines.push(indent('right_motor.run(right_speed)', 4))
  lines.push(indent('if progress >= 1:', 4))
  lines.push(indent('break', 6))
  lines.push(indent('wait(GYRO_CFG["sample_ms"])', 4))
  lines.push(indent('left_motor.stop(Stop.HOLD)'))
  lines.push(indent('right_motor.stop(Stop.HOLD)'))
  lines.push('')
  lines.push('SEGMENTS = [')
  segmentPayload.forEach((segment) => {
    const entries = [
      `"type": "${segment.type}"`,
      `"enabled": ${toPythonBool(segment.enabled)}`,
      `"auto": ${toPythonBool(segment.auto)}`,
      `"start_heading_deg": ${segment.start_heading_deg}`,
      `"end_heading_deg": ${segment.end_heading_deg}`,
    ]
    if (segment.length_mm !== undefined) entries.push(`"length_mm": ${segment.length_mm}`)
    if (segment.heading_deg !== undefined) entries.push(`"heading_deg": ${segment.heading_deg}`)
    if (segment.radius_mm !== undefined) entries.push(`"radius_mm": ${segment.radius_mm}`)
    if (segment.angle_deg !== undefined) entries.push(`"angle_deg": ${segment.angle_deg}`)
    if (segment.entry_heading_deg !== undefined) entries.push(`"entry_heading_deg": ${segment.entry_heading_deg}`)
    if (segment.control) entries.push(`"control": "${segment.control}"`)
    if (segment.profile) entries.push(`"profile": ${JSON.stringify(segment.profile)}`)
    lines.push(indent(`{ ${entries.join(', ')} },`, 2))
  })
  lines.push(']')
  lines.push('')
  lines.push('def execute_segment(segment):')
  lines.push(indent('label = segment["label"]'))
  lines.push(indent('print(f"Starting {label}")'))
  lines.push(indent('start_time = watch.time()'))
  lines.push(indent('if not segment["enabled"]:', 4))
  lines.push(indent('print("  skipped (disabled)")', 6))
  lines.push(indent('return', 6))
  lines.push(indent('if segment["type"] == "line":', 4))
  lines.push(indent('drive_line(segment)', 6))
  lines.push(indent('elif segment["type"] == "arc":', 4))
  lines.push(indent('drive_arc(segment)', 6))
  lines.push(indent('elif segment["type"] == "turn":', 4))
  lines.push(indent('turn_in_place(segment)', 6))
  lines.push(indent('elapsed = watch.time() - start_time'))
  lines.push(indent('print(f"  done in {elapsed} ms")'))
  lines.push('')
  lines.push('def main():')
  lines.push(indent('hub.imu.reset_heading(0)'))
  lines.push(indent('watch.reset()'))
  lines.push(indent('for segment in SEGMENTS:'))
  lines.push(indent('execute_segment(segment)', 4))
  lines.push(indent('left_motor.stop(Stop.HOLD)'))
  lines.push(indent('right_motor.stop(Stop.HOLD)'))
  lines.push(indent('print("Path complete")'))
  lines.push(indent('wait(500)'))
  lines.push('')
  lines.push('main()')

  return lines.join('\n')
}

export const generateSvgExport = (
  doc: PathDocument,
  segments: ResolvedSegment[],
) => {
  const width = 800
  const height = 800
  const margin = 40
  const points = segments.flatMap((segment) => segment.geometry.points)
  let minX = Math.min(...points.filter((_, idx) => idx % 2 === 0))
  let maxX = Math.max(...points.filter((_, idx) => idx % 2 === 0))
  let minY = Math.min(...points.filter((_, idx) => idx % 2 === 1))
  let maxY = Math.max(...points.filter((_, idx) => idx % 2 === 1))
  if (!Number.isFinite(minX) || !Number.isFinite(maxX)) {
    minX = -200
    maxX = 200
    minY = -200
    maxY = 200
  }
  const scale = Math.min(
    (width - margin * 2) / (maxX - minX || 1),
    (height - margin * 2) / (maxY - minY || 1),
  )

  const transformPoint = (x: number, y: number) => {
    const px = (x - minX) * scale + margin
    const py = height - ((y - minY) * scale + margin)
    return { x: px, y: py }
  }

  const segmentPaths = segments
    .map((segment) => {
      const pathPoints: string[] = []
      for (let i = 0; i < segment.geometry.points.length; i += 2) {
        const x = segment.geometry.points[i]
        const y = segment.geometry.points[i + 1]
        const point = transformPoint(x, y)
        pathPoints.push(`${point.x.toFixed(2)},${point.y.toFixed(2)}`)
      }
      const color = segment.type === 'line' ? '#2563eb' : segment.type === 'arc' ? '#f97316' : '#111827'
      return `<polyline fill="none" stroke="${color}" stroke-width="2" points="${pathPoints.join(' ')}" />`
    })
    .join('\n')

  const waypointLabels = doc.waypoints
    .map((wp) => {
      const pt = transformPoint(wp.x, wp.y)
      return `<circle cx="${pt.x.toFixed(2)}" cy="${pt.y.toFixed(2)}" r="4" fill="#16a34a" />\n<text x="${pt.x.toFixed(2)}" y="${(pt.y - 8).toFixed(2)}" font-size="12" text-anchor="middle" fill="#14532d">${sanitizeLabel(wp.name)}</text>`
    })
    .join('\n')

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">
  <style>
    text { font-family: 'Inter', sans-serif; }
  </style>
  <rect width="100%" height="100%" fill="#f8fafc" />
  ${segmentPaths}
  ${waypointLabels}
</svg>`
}
