import type {
  ArcSegment,
  AutoCornerMode,
  Pose,
  ResolvedSegment,
  Segment,
  TurnSegment,
  ValidationWarning,
} from '../types'
import {
  advancePose,
  clamp,
  normalizeDegrees,
  toRadians,
} from './geometry'

interface CornerPlan {
  type: 'fillet' | 'turn'
  angleDeg: number
  radiusMm?: number
  offsetMm?: number
}

interface ResolveOptions {
  segments: Segment[]
  initialPose?: Pose
  settings: {
    autoCorners: {
      mode: AutoCornerMode
      minRadiusMm: number
      maxFilletSweepDeg: number
    }
  }
}

const getEntryHeading = (segment: Segment, defaultHeading: number): number => {
  switch (segment.type) {
    case 'line':
      return segment.headingDeg
    case 'arc':
      return segment.entryHeadingDeg ?? defaultHeading
    case 'turn':
      return defaultHeading
  }
}

const getExitHeading = (
  segment: Segment,
  startHeading: number,
): number => {
  switch (segment.type) {
    case 'line':
      return segment.headingDeg
    case 'arc':
      return (segment.entryHeadingDeg ?? startHeading) + segment.angleDeg
    case 'turn':
      return startHeading + segment.angleDeg
  }
}

const computeCornerPlan = (
  current: Segment,
  next: Segment | undefined,
  startHeading: number,
  currentTrimStart: number,
  nextTrimStart: number,
  settings: ResolveOptions['settings'],
): CornerPlan | undefined => {
  if (!next || !current.enabled || !next.enabled) return undefined

  const exitHeading = getExitHeading(current, startHeading)
  const entryHeadingNext = getEntryHeading(next, exitHeading)
  const delta = normalizeDegrees(entryHeadingNext - exitHeading)
  if (Math.abs(delta) < 1e-3) return undefined

  if (settings.autoCorners.mode === 'off') {
    return undefined
  }

  if (
    settings.autoCorners.mode !== 'turn_only' &&
    current.type === 'line' &&
    next.type === 'line'
  ) {
    const currentRemaining = Math.max(0, current.lengthMm - currentTrimStart)
    const nextRemaining = Math.max(0, next.lengthMm - nextTrimStart)
    const absDelta = Math.abs(delta)
    if (absDelta <= settings.autoCorners.maxFilletSweepDeg) {
      const deltaRad = Math.abs(toRadians(delta))
      const tanHalf = Math.tan(deltaRad / 2)
      if (tanHalf > 1e-6) {
        const maxRadius = Math.min(currentRemaining, nextRemaining) / tanHalf
        if (maxRadius >= settings.autoCorners.minRadiusMm) {
          const radius = clamp(
            settings.autoCorners.minRadiusMm,
            settings.autoCorners.minRadiusMm,
            maxRadius,
          )
          const offset = radius * tanHalf
          if (currentRemaining > offset + 1 && nextRemaining > offset + 1) {
            return {
              type: 'fillet',
              angleDeg: delta,
              radiusMm: radius,
              offsetMm: offset,
            }
          }
        }
      }
    }
  }

  return {
    type: 'turn',
    angleDeg: delta,
  }
}

const makeResolvedLine = (
  id: string,
  sourceId: string,
  start: Pose,
  headingDeg: number,
  lengthMm: number,
  segment: Segment,
): ResolvedSegment => {
  const { x, y } = advancePose(start.x, start.y, headingDeg, lengthMm)
  return {
    id,
    sourceId,
    type: 'line',
    start,
    end: { x, y, headingDeg },
    geometry: { points: [start.x, start.y, x, y] },
    segment,
    autoGenerated: id !== sourceId,
  }
}

const makeResolvedArc = (
  id: string,
  sourceId: string,
  start: Pose,
  entryHeading: number,
  radiusMm: number,
  angleDeg: number,
  segment: Segment,
): ResolvedSegment => {
  const dir = angleDeg >= 0 ? 1 : -1
  const headingRad = toRadians(entryHeading)
  const startAngle = headingRad - dir * Math.PI / 2
  const centerX = start.x + radiusMm * Math.cos(startAngle)
  const centerY = start.y + radiusMm * Math.sin(startAngle)
  const sweepRad = toRadians(angleDeg)
  const endAngle = startAngle + sweepRad
  const endX = centerX + radiusMm * Math.cos(endAngle)
  const endY = centerY + radiusMm * Math.sin(endAngle)
  const endHeading = entryHeading + angleDeg
  const points = [] as number[]
  const steps = Math.max(16, Math.ceil(Math.abs(angleDeg) / 10))
  for (let i = 0; i <= steps; i += 1) {
    const t = i / steps
    const angle = startAngle + sweepRad * t
    points.push(centerX + radiusMm * Math.cos(angle))
    points.push(centerY + radiusMm * Math.sin(angle))
  }
  return {
    id,
    sourceId,
    type: 'arc',
    start,
    end: { x: endX, y: endY, headingDeg: endHeading },
    geometry: { points, center: { x: centerX, y: centerY }, radiusMm },
    segment,
    autoGenerated: id !== sourceId,
  }
}

const makeResolvedTurn = (
  id: string,
  sourceId: string,
  start: Pose,
  angleDeg: number,
  segment: Segment,
): ResolvedSegment => {
  const endHeading = start.headingDeg + angleDeg
  return {
    id,
    sourceId,
    type: 'turn',
    start,
    end: { ...start, headingDeg: endHeading },
    geometry: { points: [start.x, start.y] },
    segment,
    autoGenerated: id !== sourceId,
  }
}

export interface ResolveResult {
  segments: ResolvedSegment[]
  warnings: ValidationWarning[]
}

export const resolveSegments = ({
  segments,
  initialPose = { x: 0, y: 0, headingDeg: 0 },
  settings,
}: ResolveOptions): ResolveResult => {
  const resolved: ResolvedSegment[] = []
  const warnings: ValidationWarning[] = []
  const trimStart = new Map<string, number>()
  let pose: Pose = { ...initialPose }

  for (let index = 0; index < segments.length; index += 1) {
    const segment = segments[index]
    const trimHead = trimStart.get(segment.id) ?? 0
    trimStart.delete(segment.id)

    const next = segments[index + 1]
    const nextTrimStart = next ? trimStart.get(next.id) ?? 0 : 0
    const plan = computeCornerPlan(
      segment,
      next,
      pose.headingDeg,
      trimHead,
      nextTrimStart,
      settings,
    )

    const trimTail = plan?.type === 'fillet' ? plan.offsetMm ?? 0 : 0
    const startPose: Pose = { ...pose }

    if (!segment.enabled) {
      warnings.push({
        id: `segment-disabled-${segment.id}`,
        message: `Segment ${segment.label ?? segment.id} is disabled.`,
        severity: 'warning',
        scope: 'segment',
        segmentId: segment.id,
      })
    }

    let segmentResolved: ResolvedSegment | undefined

    if (segment.type === 'line') {
      const effectiveLength = Math.max(0, segment.lengthMm - trimHead - trimTail)
      segmentResolved = makeResolvedLine(
        segment.id,
        segment.id,
        startPose,
        segment.headingDeg,
        effectiveLength,
        segment,
      )
      pose = { ...segmentResolved.end }
    } else if (segment.type === 'arc') {
      const entryHeading = segment.entryHeadingDeg ?? pose.headingDeg
      segmentResolved = makeResolvedArc(
        segment.id,
        segment.id,
        startPose,
        entryHeading,
        segment.radiusMm,
        segment.angleDeg,
        segment,
      )
      pose = { ...segmentResolved.end }
    } else {
      segmentResolved = makeResolvedTurn(
        segment.id,
        segment.id,
        startPose,
        segment.angleDeg,
        segment,
      )
      pose = { ...segmentResolved.end }
    }

    resolved.push(segmentResolved)

    if (plan?.type === 'fillet' && next) {
      trimStart.set(next.id, (trimStart.get(next.id) ?? 0) + (plan.offsetMm ?? 0))
      if (segment.type === 'line' && next.type === 'line') {
        const startForFillet = { ...pose }
        const arcSegment: ArcSegment = {
          id: `auto-fillet-${segment.id}-${next.id}`,
          type: 'arc',
          radiusMm: plan.radiusMm ?? settings.autoCorners.minRadiusMm,
          angleDeg: plan.angleDeg,
          entryHeadingDeg: segmentResolved.end.headingDeg,
          profile: { ...segment.profile },
          enabled: true,
          label: 'Auto fillet',
          notes: 'Generated corner fillet',
        }
        const filletResolved = makeResolvedArc(
          arcSegment.id,
          segment.id,
          startForFillet,
          arcSegment.entryHeadingDeg,
          arcSegment.radiusMm,
          arcSegment.angleDeg,
          arcSegment,
        )
        resolved.push(filletResolved)
        pose = { ...filletResolved.end }
      }
    } else if (plan?.type === 'turn') {
      const turnSegment: TurnSegment = {
        id: `auto-turn-${segment.id}-${next?.id ?? 'end'}`,
        type: 'turn',
        angleDeg: plan.angleDeg,
        profile: {
          shape: 'trapezoid',
          startDegS: 0,
          cruiseDegS: 90,
          endDegS: 0,
          accelDegS2: 400,
          decelDegS2: 400,
        },
        control: 'gyro',
        enabled: true,
        label: 'Auto corner turn',
        notes: 'Generated corner turn',
      }
      const turnResolved = makeResolvedTurn(
        turnSegment.id,
        segment.id,
        { ...pose },
        plan.angleDeg,
        turnSegment,
      )
      resolved.push(turnResolved)
      pose = { ...turnResolved.end }
    }
  }

  return { segments: resolved, warnings }
}
