export type MotorPort = 'A' | 'B' | 'C' | 'D' | 'E' | 'F'

export type ProfileShape = 'trapezoid' | 's_curve'

export interface LinearSpeedProfile {
  shape: ProfileShape
  startMmS: number
  cruiseMmS: number
  endMmS: number
  accelMmS2: number
  decelMmS2: number
  inheritStart?: boolean
}

export interface AngularSpeedProfile {
  shape: ProfileShape
  startDegS: number
  cruiseDegS: number
  endDegS: number
  accelDegS2: number
  decelDegS2: number
  inheritStart?: boolean
}

export type SegmentType = 'line' | 'arc' | 'turn'

export interface SegmentBase {
  id: string
  type: SegmentType
  label?: string
  notes?: string
  enabled: boolean
}

export interface LineSegment extends SegmentBase {
  type: 'line'
  lengthMm: number
  headingDeg: number
  profile: LinearSpeedProfile
}

export interface ArcSegment extends SegmentBase {
  type: 'arc'
  radiusMm: number
  angleDeg: number
  entryHeadingDeg: number
  profile: LinearSpeedProfile
}

export type TurnControlMode = 'gyro' | 'encoders'

export interface TurnSegment extends SegmentBase {
  type: 'turn'
  angleDeg: number
  profile: AngularSpeedProfile
  control: TurnControlMode
}

export type Segment = LineSegment | ArcSegment | TurnSegment

export interface Waypoint {
  id: string
  name: string
  x: number
  y: number
  notes?: string
  enabled: boolean
}

export interface RobotDefaults {
  lineMmS: number
  arcMmS: number
  turnDegS: number
  accelMmS2: number
  decelMmS2: number
}

export interface GyroConfig {
  enabled: boolean
  kp: number
  ki: number
  kd: number
  sampleMs: number
  maxCorrectionDegS: number
  toleranceDeg: number
}

export interface RobotConfig {
  ports: {
    left: MotorPort
    right: MotorPort
    aux: { id: string; port: MotorPort }[]
  }
  invert: {
    left: boolean
    right: boolean
    aux: Record<string, boolean>
  }
  wheel: {
    source: 'diameter' | 'circumference'
    diameterMm: number
    circumferenceMm: number
  }
  trackWidthMm: number
  gearRatio: number
  gyro: GyroConfig
  defaults: RobotDefaults
}

export type AutoCornerMode = 'fillet_then_turn' | 'turn_only' | 'off'

export interface AutoCornerSettings {
  mode: AutoCornerMode
  minRadiusMm: number
  maxFilletSweepDeg: number
}

export interface PathSettings {
  autoCorners: AutoCornerSettings
}

export interface PathMeta {
  version: string
  units: {
    distance: 'mm'
    angle: 'deg'
  }
  title: string
  createdAt: string
}

export interface PathModel {
  meta: PathMeta
  robot: RobotConfig
  settings: PathSettings
  segments: Segment[]
  waypoints: Waypoint[]
}

export interface Pose {
  x: number
  y: number
  headingDeg: number
}

export interface ResolvedSegment {
  id: string
  sourceId: string
  type: SegmentType
  start: Pose
  end: Pose
  geometry: {
    points: number[]
    center?: { x: number; y: number }
    radiusMm?: number
  }
  segment: Segment
  autoGenerated: boolean
}

export interface ValidationWarning {
  id: string
  message: string
  severity: 'warning' | 'error'
  scope: 'robot' | 'segment' | 'path'
  segmentId?: string
}
